/************ Add: Sequences ***************/

/* Autogenerated Sequences */

CREATE SEQUENCE "public"."LIBRO_Id_seq" INCREMENT BY 1 START 1;
COMMENT ON SEQUENCE "public"."LIBRO_Id_seq" IS 'DbWrench Autogenerated Sequence.';




/************ Update: Tables ***************/

/******************** Add Table: "public"."LIBRO" ************************/

/* Build Table Structure */
CREATE TABLE "public"."LIBRO"
(
	"Id" INTEGER DEFAULT nextval('public."LIBRO_Id_seq"'::regclass) NOT NULL,
	titulo VARCHAR(100) NULL,
	anio DATE NULL,
	autor VARCHAR(100) NULL,
	imprenta VARCHAR(100) NULL,
	disponible INTEGER NULL
);

/* Add Primary Key */
ALTER TABLE "public"."LIBRO" ADD CONSTRAINT "pkLIBRO"
	PRIMARY KEY ("Id");